//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetCore.PluginManager.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspNetCore.PluginManager.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Id&quot;:10,&quot;Name&quot;:&quot;Custom Page 10&quot;,&quot;Content&quot;:[{&quot;AssemblyQualifiedName&quot;:&quot;DynamicContent.Plugin.Templates.HtmlTextTemplate, DynamicContent.Plugin, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null&quot;,&quot;EditorAction&quot;:&quot;/DynamicContent/TextTemplateEditor/&quot;,&quot;Name&quot;:&quot;Html Content&quot;,&quot;SortOrder&quot;:0,&quot;HeightType&quot;:2,&quot;Height&quot;:-1,&quot;WidthType&quot;:0,&quot;Width&quot;:12,&quot;Data&quot;:&quot;&lt;p&gt;This is &lt;br /&gt;html over&lt;br /&gt;three lines&lt;/p&gt;&quot;,&quot;ActiveFrom&quot;:&quot;0001-01-01T00:00:00&quot;,&quot;ActiveTo&quot;:&quot;9999-12-31T23:59:59.9999999&quot;,&quot;UniqueId&quot;:&quot;control-1&quot;,&quot;ColumnCount&quot;:12} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DynamicContent10Items {
            get {
                return ResourceManager.GetString("DynamicContent10Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Id&quot;:10,&quot;Name&quot;:&quot;Custom Page 10&quot;,&quot;Content&quot;:[{&quot;AssemblyQualifiedName&quot;:&quot;DynamicContent.Plugin.Templates.HtmlTextTemplate, DynamicContent.Plugin, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null&quot;,&quot;EditorAction&quot;:&quot;/DynamicContent/TextTemplateEditor/&quot;,&quot;Name&quot;:&quot;Html Content&quot;,&quot;SortOrder&quot;:0,&quot;HeightType&quot;:2,&quot;Height&quot;:-1,&quot;WidthType&quot;:0,&quot;Width&quot;:12,&quot;Data&quot;:&quot;&lt;p&gt;This is &lt;br /&gt;html over&lt;br /&gt;three lines&lt;/p&gt;&quot;,&quot;ActiveFrom&quot;:&quot;0001-01-01T00:00:00&quot;,&quot;ActiveTo&quot;:&quot;9999-12-31T23:59:59.9999999&quot;,&quot;UniqueId&quot;:&quot;control-1&quot;,&quot;ColumnCount&quot;:12} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DynamicContent1Item {
            get {
                return ResourceManager.GetString("DynamicContent1Item", resourceCulture);
            }
        }
    }
}
